name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (optional, if you want to do build locally)
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /cloudsineAI_assessment_backend
            echo "Stopping existing container (if any)..."
            docker stop cloudsine_backend || true
            docker rm cloudsine_backend || true

            echo "Building Docker image..."
            docker build -t cloudsine_backend .

            echo "Running Docker container..."
            docker run -d -p 8000:8000 --name cloudsine_backend cloudsine_backend
          EOF
