name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (optional, if you want to do build locally)
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/cloudsineAI_assessment_backend
            git pull origin
            echo "Stopping existing container (if any)..."
            sudo docker stop cloudsine_backend || true
            sudo docker rm cloudsine_backend || true

            echo "Building Docker image..."
            sudo docker build -t cloudsine_backend .

            echo "Running Docker container..."
            sudo docker run -d --network="host" --name cloudsine_backend cloudsine_backend
          
            echo "Confgure Nginx..."
            sudo cp /home/ubuntu/cloudsineAI_assessment_backend/nginx/fastapi.conf /etc/nginx/sites-available/cloudsine_backend
            sudo ln -sf /etc/nginx/sites-available/cloudsine_backend /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx
          EOF
